### ISSUE TITLE
`make installcheck` fails with PostgreSQL 9.6

### ISSUE THREAD

**Issue by a3nm** [PierreSenellart/provsql#1]
Hi Pierre,

I tried to make ProvSQL work on a new machine with PostgreSQL 9.6. Compiling, installing, and enabling worked fine, but `make installcheck` fails as follows: [regression.diffs.txt](https://github.com/PierreSenellart/provsql/files/682515/regression.diffs.txt) [regression.out.txt](https://github.com/PierreSenellart/provsql/files/682516/regression.out.txt).

Are you having the same problem? It's possible that I did something wrong :) but hopefully the tests should fail in a more understandable way if it's something stupid (e.g., the library is not loaded at all), especially given the fact that the first two tests appear to succeed.

**Comment by PierreSenellart** [comment]
Fixed in 759a279b2a1733890c91031d4151a658ab723d85.

**Comment by a3nm** [comment]
Indeed, this fixes the problem. Thanks!

-- 
Antoine Amarilli
