### ISSUE TITLE
ProvSQL does not remove provsql column in "SELECT * FROM" appearing in nested queries

### ISSUE THREAD

**Issue by louisjac** [PierreSenellart/provsql#14]
Suppose I have two tables a and b each with one value and some provenance annotation such as:

```
SELECT * FROM a  ;

 f  |               provsql                
----+--------------------------------------
 42 | 1b23ea2f-c54d-400a-86ad-172610fe611b
(1 row)


SELECT * FROM b;
 f  |               provsql                
----+--------------------------------------
 42 | 5a078cbd-292c-468d-ae59-9ab756336a46
(1 row)
```

When I query "SELECT * FROM a UNION SELECT * FROM b" I expect (and get) one output tuple with f=42 and a provenance annotation (corresponding to 1b23ea2f-c54d-400a-86ad-172610fe611b +  5a078cbd-292c-468d-ae59-9ab756336a46) but if the union is nested (i.e. SELECT * FROM (SELECT * FROM a UNION SELECT * FROM b) t ) then we have two results:

```

 f  |               provsql                
----+--------------------------------------
 42 |  5a078cbd-292c-468d-ae59-9ab756336a46
 42 |  1b23ea2f-c54d-400a-86ad-172610fe611b
(2 rows)


```

The reason seems to be that ProvSQL does not remove the provsql column when the * is nested and thus the union is transformed into a group by over the columns f and provsql.

Here is my example: [test.txt](https://github.com/PierreSenellart/provsql/files/2957236/test.txt)

I have a patch d8edeccb9aaf4ec67a4ee390cca511132dcab5e1 but this is not completely satisfactory. ProvSQL should probably do a first pass where we remove provsql from each list of columns of the query?

**Comment by PierreSenellart** [comment]
Thanks for the bug report. Fixed. The first pass you mentioned did exist, but it was only done for the main query, not for subqueries, because I erroneously thought it would not matter for subqueries. I just had to apply the pass to subqueries as well.

**Comment by louisjac** [comment]
Perfect! I noticed this part of the rewriting avoiding subqueries but it thought it was useful for some other reason.
