### ISSUE TITLE
Docker install: "make: *** No targets specified and no makefile found.  Stop."   error when running docker build .

### ISSUE THREAD

**Issue by CloudSpark** [PierreSenellart/provsql#20]
Hello.
When building the Docker image after cloning the repo to my Ubuntu 18.04 machine, I am getting an error on step 26
I have attached the output of the Docker build.
Is there something I am missing?
[buildlogfile.txt](https://github.com/PierreSenellart/provsql/files/6594934/buildlogfile.txt)

**Comment by PierreSenellart** [comment]
The docker build was not launched from the root of the repository. The proper way to build is to launch:
```
docker build -f docker/Dockerfile .
```
from the root of the Git repository. To make this clearer, I have added (commit 76a744b) a target "docker-build" to the main [Makefile](https://github.com/PierreSenellart/provsql/blob/master/Makefile) and some instructions to the [README](https://github.com/PierreSenellart/provsql/blob/master/doc/provsql.md).

Finally, also note that you usually don't need to build the Docker container yourself but can get it from Docker Hub using
```
docker run inriavalda/provsql
```
