### ISSUE TITLE
Unable to find procedure on how to connect ProvSQL installed in Docker to another Docker postgresql container.

### ISSUE THREAD

**Issue by CloudSpark** [PierreSenellart/provsql#21]
We are setting up the ProvSQL Docker container and have our PostgreSQL database running in a different Docker container.
Is there a document that describes how to achieve this?

**Comment by PierreSenellart** [comment]
This is not possible: ProvSQL includes a shared library that needs to be directly loaded by the PostgreSQL executable (and that needs to be compiled against the specific version of PostgreSQL installed). If you need the PostgreSQL DBMS to be in a Docker container, the only option I can see is to install ProvSQL within the same container.
