### ISSUE TITLE
ERROR:  extension "provsql" has no installation script nor update path for version "1.0.0-dev"

### ISSUE THREAD

**Issue by CloudSpark** [PierreSenellart/provsql#23]
Hello.
One of our team is trying to test provsql on one of our postgres 12 databases and is getting an error I am unsure about resolving. Have you seen this before? (The db name is 'mdias')

mdias=# CREATE EXTENSION provsql;

ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/provsql.control": No such file or directory

I created the file in the directory and then reran the CREATE EXTENSION command. This is the error msg:
ERROR:  extension "provsql" has no installation script nor update path for version "1.0.0-dev"

\# provsql extension
comment = 'Semiring provenacne for PostgreSQL databases'
default_version = '1.0.0-dev'
requires = 'uuid-ossp'
elocatable = false
module_pathname = '$libdir/provsql'

**Comment by PierreSenellart** [comment]
These error messages suggest that ProvSQL has not been properly installed. It is never necessary to write a provsql.control file by hand. Please make sure to follow all installation steps:

1. Compile the code with make. If you have several installed versions of PostgreSQL, you can change the version the module is compiled against by changing the reference to pg_config in the Makefile.internal file.

2. Install it in the PostgreSQL extensions directory with make install (run as a user with rights to write to the PostgreSQL installation directories).

3. Add the line
    ```shared_preload_libraries = 'provsql'```
    to the postgresql.conf configuration file (on Linux systems, it should be in /etc/postgresql/VERSION/main/postgresql.conf) and restart the PostgreSQL server (e.g., with service postgresql restart on systemd-based distributions). This is required because the extension includes hooks.

**Comment by PierreSenellart** [comment]
Closing in the absence of further comments on this bug report.
