### ISSUE TITLE
No targets specified during Docker build

### ISSUE THREAD

**Issue by CloudSpark** [PierreSenellart/provsql#24]
Hello again...
I am running a Docker build using your latest master code and am getting this error:

`Step 22/38 : RUN make
 ---> Running in b47f2e128cf0
make: *** No targets specified and no makefile found.  Stop.`

I will attach the output of the build process.
[MobaXterm_mdias-dev12Steve_20210730_163409.txt](https://github.com/PierreSenellart/provsql/files/6909911/MobaXterm_mdias-dev12Steve_20210730_163409.txt)

**Comment by PierreSenellart** [comment]
See  #20. The Docker build was not properly launched. The proper way to run the Docker build is to launch
```
docker build -f docker/Dockerfile .
```
or, more simply,
```
make docker-build
```
from the root of the ProvSQL repository.
