### ISSUE TITLE
Docker install: Is it possible to store the database on persistent storage with ProvSQL?

### ISSUE THREAD

**Issue by CloudSpark** [PierreSenellart/provsql#25]
I've been trying fruitlessly to get our Dockerfile and docker-compose.yml to place the PostgreSQL data directory on a mounted volume on the host and was hoping you may have set this up in an alternative configuration.

**Comment by PierreSenellart** [comment]
I haven't tried that, but ProvSQL does not change anything to the way PostgreSQL store its data; if you manage to get a Docker container for PostgreSQL with data stored on an external storage (it should just be a matter of changing the `data_directory` variable in the PostgreSQL configuration file), the same can be done for a ProvSQL install. If you have issues specific to ProvSQL, please open a new issue, but ProvSQL does not directly access the data directory, everything is done through PostgreSQL.
