### ISSUE TITLE
Out of shared memory for large database

### ISSUE THREAD

**Issue by mini-1235** [PierreSenellart/provsql#29]
Hi, I am recently making every table of my databse [imdb](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/2QYZBT) to be provsql aware. However, when I started to run add_provenance for every table, it reported an error saying that out of shared memory, I have tried modifying the related parameters in the postgresql configuration file such as shared_buffers, max_transactions, work_mem, but still having the same error. I have seen the previous issue mentioning that provsql is not suitable for large database, is there any update for this?

**Comment by mini-1235** [comment]
Updates: I increase both the max_nb_gates, init_nb_gates, and also increase the shared_buffers in the configuration file, and it is working now

**Comment by PierreSenellart** [comment]
Great that you were able to make it work by increasing the amount of shared memories and corresponding ProvSQL parameters ­– it is indeed the way to go, though it is not really a scalable solution, as this require a potentially large quantity of RAM, and the RAM requirements will raise as queries are made to the database, increasing provenance circuit size.

We have an implementation of ProvSQL that relies purely on disk (in-database) storage of provenance – it is currently a bit hidden in a branch and not directly usable but I could make it usable fairly quickly; the downside is that it is slower than in-memory storage of the circuit. Let me know if this is something you may be interested in.

In the long term, the way to go is definitely to mix both with persistent in-database storage of the circuit with shared memory caching of parts of it, but this requires significant engineering work, and I don't have resources to work on this right now.

I am closing this issue right now as resolved, but feel free to contact me off-Github at pierre@senellart.com if you would like to discuss about the way you are using ProvSQL and if anything can be done to make it work smoother in your case.
