### ISSUE TITLE
Postgresql segfault

### ISSUE THREAD

**Issue by louisjac** [PierreSenellart/provsql#8]
It seems PostgreSQL segaults when compiling queries of the form SELECT ... WHERE EXISTS.

Using the example, it segfaults on:

`SELECT formula(provenance(),'personnel_name') WHERE EXISTS (SELECT FROM personnel) ;
`
or even on:
`
EXPLAIN SELECT formula(provenance(),'personnel_name') WHERE EXISTS (SELECT FROM personnel) ;`

I have not looked into it but it is probably due to an unsupported feature in the compilation.

**Comment by PierreSenellart** [comment]
Fixed in e3d8be3; the problem was not with the EXISTS clause, but that the query had no "FROM" clause. On such queries, provenance is meaningless. Fixed the source of the crash, and queries with no FROM clause are now not processed by ProvSQL.
